### ISSUE TITLE
multi tenant

### ISSUE THREAD

**Issue by matiazar** [rawilk/laravel-settings#55] opened 2024-01-18 13:02 UTC
### Laravel Settings

v3.3

### Laravel Version

v10

### Bug description

Hi. can any one tell me if I need to do anything to work with tenants?

thanks in advance

**Comment by rawilk** [comment] 2024-01-21 22:11
Depends on what you're doing for multi-tenancy. I use spatie's package for multi-tenancy, and I'm using a single database, so I'm making use of the [teams](https://randallwilk.dev/docs/laravel-settings/v3/basic-usage/teams) feature of this package. Basically, I'm using a "team" as a tenant for my use case. 

I have a task that gets run whenever a tenant is made current that sets the team id on the settings service. This is accomplished using `settings()->setTeamId($tenantId);`

**Comment by matiazar** [comment] 2024-01-23 22:42
yes I used stancl tenant with multi db.. so I didnt need to change anything... thanks!

**Comment by rawilk** [comment] 2024-03-10 22:34
I'm going to close this issue since it appears to be working as intended for you. Feel free to re-open in the future if necessary.

**Closed by rawilk** 2024-03-10 22:34 UTC

**Comment by rawilk** [comment] 2025-03-14 18:39
You may need to set a cache key prefix for each tenant. I'm not sure how your multi-tenant package works with switching tenants, but with mine I just prefix the cache key for certain things like settings whenever a tenant context is changed through a switch tenant task.

**Comment by matiazar** [comment] 2025-03-14 18:44
thanks for answering me.
Im using this package
https://tenancyforlaravel.com/docs/v3/quickstart/

**Comment by rawilk** [comment] 2025-03-14 18:51
I'm sure there's a way for you to perform certain tasks whenever a tenant context is activated with it like I can with the package I'm using. Basically all you need to do is hook into that and update the config value for the cache key prefix when that happens. Here is a basic example of what I do in one of my applications:

```php
class SwitchConfigTask extends SwitchTenantTask
{
    private ?string $originalSettingsCacheKey;

    public function __construct()
    {
        $this->originalSettingsCacheKey = config('settings.cache_key_prefix');
    }

    public function makeCurrent($tenant): void
    {
        config()->set('settings.cache_key_prefix', "{$this->originalSettingsCacheKey}_tenant_{$tenant->getKey()}");
    }

    public function forgetCurrent(): void
    {
        config()->set('settings.cache_key_prefix', $this->originalSettingsCacheKey);
    }
}
```

Your mileage may vary, but that's basically the gist of what needs to happen.

**Comment by matiazar** [comment] 2025-03-26 18:36
did it. thanks!!
